# Generated by Django 4.2.4 on 2023-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies_app', '0003_rename_post_reply_post_id_alter_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
