# Generated by Django 4.2.4 on 2023-08-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_user_display_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
